### ISSUE TITLE
On adding more competitions

### ISSUE THREAD

**Issue by davidardagh** [mlcontests/mlcontests.github.io#24]
Hey guys, 

On the topic of adding more competitions: 

We normally run machine learning competitions and we've got a new project. We've created a community project with leading experts to model the combined health and economic impact of different lockdown exit strategies. We already have data scientists signed up from top firms (Microsoft, Amazon, Twitter).

There is a page here: https://quant-quest.com/landingPage/helpproject 
and an Eventbrite here: https://www.eventbrite.co.uk/e/help-project-modelling-the-health-and-economic-impacts-of-exiting-lockdown-tickets-104985977886 .

he project is starting on Monday (18th) and will initially run for 2 weeks, but will almost definitely continue beyond that. I know its a little different to the normal stuff we do, but it would be really great to get it up on your site.

Best,
David

**Comment by hcarlens** [comment]
Hi David,

That looks like a great project. I'd be happy to link to it, just figuring out how best to do that. At the moment our main page only lists competitions with monetary prizes. 

Will there be any prizes for your project? If so I'll just put it on the main page. 

Otherwise we could add it to the main page with a $0 prize, or create a new list for contests which don't have prizes. 

Good luck with the project!
Harald

**Comment by davidardagh** [comment]
Yeh this competition doesn't have a prize in the way our competitions normally do. 

Best,
David
