### ISSUE TITLE
Sorting strings instead of numbers

### ISSUE THREAD

**Issue by guilhermelowa** [mlcontests/mlcontests.github.io#89]
When I try to sort by Deadline or Prize Pool, the results are sorted in string, not in numbers.

So when I try to sort by Deadline, I get the results:
1 May 2022
10 May 2022
11 Apr 2022
13 Mar 2022
...
6 May 2022
9 May 2022

Same issue with Prize Pool

**Comment by hcarlens** [comment]
Thanks @guilhermelowa! Yeah this is a bit annoying. Basically it sorts properly when all the data is set to be in the right format - "D MMM YYYY" for dates, and dollar amounts for the prizes. But as soon as there's a single value in there that doesn't conform (e.g. "11 April" instead of "11 Apr", or "$1,000 + merch"), it falls back to string sorting like you mentioned. 

Lots of people contribute and I don't always catch the inconsistencies when merging in. There was some discussion in [this PR](https://github.com/mlcontests/mlcontests.github.io/pull/87) about setting up a regex-based validator for the json file to ensure everything conforms to the spec, which would fix this going forward. Is that something you'd be interested in adding? Or do you have any other ideas for fixing this?

**Comment by guilhermelowa** [comment]
I see. Yes, that should be a good fix I think. Or asking for users to input in the format DD-MM-YYYY and then convert to the current format.

I wish I could add this, but right now I'm super busy looking for a job ):

Can you point me where I should make the change? On weekend if I manage to get a spare time I'll add.

**Comment by hcarlens** [comment]
I'm not super familiar with how the change would work - it would be similar to [this PR](https://github.com/mlcontests/mlcontests.github.io/pull/87), adding a validator through GitHub Actions, but using a regex for each field rather than just making sure it's valid JSON. 

The data that needs to be validated here would be the `deadline` and `prize` fields  in https://github.com/mlcontests/mlcontests.github.io/blob/master/js/competitions.json. 

I'll leave this issue open for a while, in case you or someone else looking at it wants to have a go. I've been trying to get around to it myself too but haven't had time yet. 

Good luck with the job search!

**Comment by hcarlens** [comment]
Done, sort of. There's now a regex date validator - not perfect, but it should pick up most cases where there are errors.
